### ISSUE TITLE
点下载会跳转到一个下载页面但会报错：Error: 404 Not Found.(server file path error)

### ISSUE THREAD

**Issue by SkyStreet** [LadderOperator/PedagogySquareAsistant#14]
浏览器是chrome。之前一直用的1.几版本，是手动安装到chrome上的，今天用教学立方就出现标题里的问题，然后就删除了，科学上网后在扩展程序商店里安装了最新版本的插件2.1.1（应该是），但还是同样的报错，无论是否选择背景模式都报错，然后手动开发者模式安装2.2.2还是一样，不知道这个问题能不能复现。

**Comment by LadderOperator** [comment]
教学立方现在获取文件路径已经加上了权限验证，所以跳转的链接均为空链接因此会404，这个问题无解，官方已经补上了漏洞
